version: "3.9"
services:  
  rabbitmq:
    restart: always
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_NODENAME: thuusbezorgd-rabbitmq-node
    volumes:
      - ./development/rabbitmq/data/:/var/lib/rabbitmq/
  postgres:
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1q2w3e!
    volumes:
      - ./development/postgres/data:/var/lib/postgresql/data
      - ./development/postgres/init:/docker-entrypoint-initdb.d/
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8091:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: student@hu.nl
      PGADMIN_DEFAULT_PASSWORD: 1q2w3e!
